{
 "title": "Bibites Test",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "run",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"run\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   },
   {
    "name": "scenario",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"scenario\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   },
   {
    "name": "species",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"species\",\r\n    predicate: (r) => r.scenario == \"${scenario}\" and r.run == \"${run}\",\r\n    start: -1d\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pellet Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"pellets\" and\r\n    r._field == \"count\" and\r\n    r.run == \"${run}\" and\r\n    r.scenario == \"${scenario}\"\r\n  )"
    }
   ]
  },
  {
   "title": "Pellet Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"pellets\" and\r\n    r._field == \"energy\" and\r\n    r.run == \"${run}\" and\r\n    r.scenario == \"${scenario}\"\r\n  )"
    }
   ]
  },
  { "title": "$species", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "species" },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"census\" and\r\n    r._field == \"count\" and\r\n    r.species == \"${species}\" and\r\n    r.run == \"${run}\" and\r\n    r.scenario == \"${scenario}\"\r\n  )"
    }
   ]
  },
  {
   "title": "avgDiet",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"census\" and\r\n    r._field == \"avgDiet\" and\r\n    r.species == \"${species}\" and\r\n    r.run == \"${run}\" and\r\n    r.scenario == \"${scenario}\"\r\n  )"
    }
   ]
  },
  {
   "title": "avgSpeed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"census\" and\r\n    r._field == \"avgSpeed\" and\r\n    r.species == \"${species}\" and\r\n    r.run == \"${run}\" and\r\n    r.scenario == \"${scenario}\"\r\n  )"
    }
   ]
  },
  {
   "title": "avgSize",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"census\" and\r\n    r._field == \"avgSize\" and\r\n    r.species == \"${species}\" and\r\n    r.run == \"${run}\" and\r\n    r.scenario == \"${scenario}\"\r\n  )"
    }
   ]
  },
  {
   "title": "avgBirthMaturity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"census\" and\r\n    r._field == \"avgBirthMaturity\" and\r\n    r.species == \"${species}\" and\r\n    r.run == \"${run}\" and\r\n    r.scenario == \"${scenario}\"\r\n  )"
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"census\" and\r\n    r._field == \"totalEnergy\" and\r\n    r.species == \"${species}\" and\r\n    r.run == \"${run}\" and\r\n    r.scenario == \"${scenario}\"\r\n  )"
    }
   ]
  },
  {
   "title": "avgViewAngle",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"census\" and\r\n    r._field == \"avgViewAngle\" and\r\n    r.species == \"${species}\" and\r\n    r.run == \"${run}\" and\r\n    r.scenario == \"${scenario}\"\r\n  )"
    }
   ]
  },
  {
   "title": "avgViewRadius",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"census\" and\r\n    r._field == \"avgViewRadius\" and\r\n    r.species == \"${species}\" and\r\n    r.run == \"${run}\" and\r\n    r.scenario == \"${scenario}\"\r\n  )"
    }
   ]
  }
 ]
}